### ISSUE TITLE
Remove space at bottom of viewer when spawning a popup

### ISSUE THREAD

**Issue by branimir1999** [clippydsdone/clippy-frontend#123]

**Comment by branimir1999** [comment]
There's currently an issue that is difficult to reproduce. When you create a popup by pressing 'e', it sometimes creates extra space at the bottom. I believe it does not remove the HMTL tags correctly when despawning the popup. It might be caused by hovering over different types of references (bibliography, figures, equations, ...)

**Comment by nsm18002** [comment]
2022-12-29 17:00 - 19:00 + 2022-12-30 17:00 - 19:00, 4h Bugfixing the popupwindow extending the pdfviewer window creating another scrollbar when moved "outside" of the visible pdfviewer area.

Solved by ultimately setting up a dedicated "popupEcosystem" div that is behind the pdf so that we can still mouseover all links but renders the popup windows infront of the pdf while still restricted by the area of the "popupEcosystem" by clipping any parts of the window that goes out of bounds.
